### PR TITLE
Add wrappers for crypto_aead_chacha20poly1305_*

### PR DESCRIPTION
**Pull request by aadavids**
Addresses Issue #107.

Includes both the original implementation and the IETF implementation. I've tried to follow the style of the other wrappers, but if you have any suggestions, let me know.

### CODE REVIEW

**Comment by aadavids** [comment]
Looks like the build is failing because my code uses some macros in the IETF version not present until libsodium version 1.0.9. 

What do you think would be the best way of handling this? I can remove the IETF wrappers from this pull request for now, and add them in later once you're ready to update the supported libsodium version.

**Comment by tarcieri** [comment]
@aadavids generally we have gated features on the supported libsodium versions, although I think we've largely eliminated that from the current codebase.

I would suggest checking the libsodium version and for nonsupported versions, stubbing methods with `NotImplementedError` if the version they're using is too old.

**Comment by aadavids** [comment]
I looked at the previous versions of the code and added in a version guard similar to what was present before. The build is now failing on a rubocop issue, after adding the AEAD test data, the test vectors file now has too many lines (107 vs 100 haha). 
Should we just move test_vectors.rb to the spec directory? Seems to make more sense having it there anyways. Or try to split it up?

**Comment by tarcieri** [comment]
@aadavids the test vectors are used when the library boots, so they should stay where they are.

You can probably `#rubocop:disable ClassLength` on that file though

**Comment by aadavids** [comment]
@tarcieri Ah, that makes sense now. Updated with the rubocop change.

**Comment by aadavids** [comment]
Any idea why the jruby checks are failing?

**Comment by tarcieri** [comment]
It looks like one of the dependencies requires Ruby 2.0+ now. We can probably drop support for Ruby 1.9.

**Comment by aadavids** [comment]
I removed the jruby (ruby 1.9) job from travis. It also builds against libsodium 1.0.10 now, which is the latest supported by rbnacl-libsodium.

**Comment by tarcieri** [comment]
@aadavids can you rebase on master and use master's .travis.yml?

**Comment by tarcieri** [comment]
Rebased and merged as 72841d0a777963a37cbeac059fd9feaebc201f66

**Pull request closed without merging**
